site_name: Ontario Math Graph
site_url: https://math.cluchey.ca

theme:
    name: 'material'
    logo: Resources/Excalidraw/logo.svg
    favicon: Resources/Excalidraw/logo.svg
    features:
      - search
      - search.suggest
      - search.highlight
      - search.share
      - navigation.instant
      - navigation.instant.progress
      #- navigation.sections
      - navigation.indexes
      - navigation.tracking
      - navigation.tabs
      - navigation.path
      - navigation.prune
      - navigation.top
      - navigation.footer
      - toc.follow
      - toc.integrate
    
    # Colour Schemes
    palette:
    
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: amber
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: amber
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

# Extensions
markdown_extensions:
  - footnotes
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  - toc:
      permalink: true

plugins:
  - search
  - roamlinks 

hide:
  - Resources/Excalidraw

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kluchey
      name: Mr. Cluchey on Github

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - https://cdn.jsdelivr.net/npm/mermaid@9.1.7/dist/mermaid.min.js
